### ISSUE TITLE
Questions about CT Pancrease dataset

### ISSUE THREAD

**Issue by zzzqzhou** [HiLab-git/DTC#11]
Dear author,
In this repository, you have provided the training code and LA dataset. Could you please provide the CT Pancrease dataset mentioned in your paper?
Hope for your reply.

**Comment by Luoxd1996** [comment]
Hi Zhou,
The Pancreas-CT dataset can be downloaded from https://wiki.cancerimagingarchive.net/display/Public/Pancreas-CT directly. So ......
Best,
Xiangde.
