### ISSUE TITLE
How to enter unlabeled data

### ISSUE THREAD

**Issue by gx-z** [HiLab-git/DTC#12]
How to enter the unlabeled data and in which file is it entered, thank you very much

**Comment by Luoxd1996** [comment]
Hi, 
Sorry, I am not sure what's your problem, so I just try to answer your questions in my understanding. First, "How to enter the unlabeled data", we used two labeled volumes and two unlabeled volumes to consist of a mini-batch in each iteration. Second, "which file is it entered",  the batch sampler is defined in [here](https://github.com/HiLab-git/DTC/blob/master/code/dataloaders/la_heart.py) and used in [here](https://github.com/HiLab-git/DTC/blob/master/code/train_la_dtc.py).
Best,
Xiangde.

**Comment by IIBMML** [comment]
Thank you very much for your reply！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HiLab-git/DTC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月17日(星期一) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HiLab-git/DTC] How to enter unlabeled data (#12)





 
Hi,
 Sorry, I am not sure what's your problem, so I just try to answer your questions in my understanding. First, "How to enter the unlabeled data", we used two labeled volumes and two unlabeled volumes to consist of a mini-batch in each iteration. Second, "which file is it entered",  the batch sampler is defined in here and used in here.
 Best,
 Xiangde.
