### ISSUE TITLE
How is best model selected for LA?

### ISSUE THREAD

**Issue by govindjeevan** [HiLab-git/DTC#14]
Hi,
Since there is no VAL data used in LA, how is the best model selected for testing and reporting dice?
Thanks in advance!

**Comment by adigasu** [comment]
Hi,
I too have same question. I do not see paper explaining the model selection for testing. Is it at 6000 iteration for all experiments? 
It will be helpful if you can clarify this part. 
Thanks!

**Comment by Luoxd1996** [comment]
Hi, 
Yes, we used the last iteration checkpoint for testing, but we also investigate the best model when using different seeds/GPUs/PyTorch versions. We found that the performance with slightly different when using different settings(~0.8% drop or gain). The released model is based on different seeds and we chose a better one. BTW, for a fair comparison, we recommend you do all experiments with the same hardware (GPU and CPU) and software (CUDA, PyTorch, Python, Numpy, and so on) or do many times and report the mean results.
Best,
Xiangde.

**Comment by Luoxd1996** [comment]
Moreover, we have transferred to the [SSL4MIS](https://github.com/HiLab-git/SSL4MIS) project, where more methods and datasets (with training, validation, testing splits) are provided. Maybe, It can give a more fair and more straightforward comparison.
