### ISSUE TITLE
About the  level-set function

### ISSUE THREAD

**Issue by 18677064404** [HiLab-git/DTC#16]
Hi,
Thanks for your great work!

Can you tell me how to  map the output of LSF task to the space of segmentation output for multi-classes. In your work,  "dis_to_mask = torch.sigmoid(-1500 * outputs_tanh)" was used to  transfer for two-classes. For multi-classes, how can I transfer?

Best.

**Comment by Luoxd1996** [comment]
Hi,
For multi-classes, one solution is splitting them into many single-class problems.
Best,
Xiangde.
