### ISSUE TITLE
An Inquiry about NIH-Pancreas dataset configuration for evaluation

### ISSUE THREAD

**Issue by ghost** [HiLab-git/DTC#17]
During study, I am so interested in your network, Dual-task Consistency﻿, and wondered the dataset configuration in training and testing.

My question is below:

 - Patient numbers in 12 labeled training sets from 82 NIH-Pancreas datasets (ex. no. 1, no. 2, ...)

 - Patient numbers in 20 testing sets from 82 NIH-Pancreas datasets (ex. no. 62, no. 63, ...)

 - Ratio of training/validation dataset in network training

If you answer the above questions, I think it will be of great help to my study.

Many thanks =)

**Comment by Luoxd1996** [comment]
Hi,
I have answered your questions in an email.
Best.
