### ISSUE TITLE
How can I get access to Pancreas CT dataset?

### ISSUE THREAD

**Issue by Kyfafyd** [HiLab-git/DTC#3]

**Comment by Luoxd1996** [comment]
Hi, Kyfafyd,
You can download the Pancreas CT data from NIH website.
Best;
Xiangde.

**Comment by Kyfafyd** [comment]
Thanks very much. Can you please provide your preprocessed dataset?

**Comment by Luoxd1996** [comment]
Just center crop and zero mean and unit variance normalization, it's very easy to implement.

**Comment by Kyfafyd** [comment]
Yes, I know. Thanks you!
But unfortunately, I can only access to server via command line without GUI. It is difficult for me to download dataset from official website.
I would appreciate it very much if you could provide google doc link.
If you are busy. Thanks once again for your time! And I will look for other help.

Thanks very much
