### ISSUE TITLE
About output shape used for compute_sdf function?

### ISSUE THREAD

**Issue by aprilaugust** [HiLab-git/DTC#5]
Thank you for the nice work!

About compute_sdf function, the VNet's outputs shape is (batch_size, num_classes, x, y, z), isn't it?

if so, the num_classes is set to 0 at outputs[:labeled_bs, 0, ...].shape (please see
https://github.com/HiLab-git/DTC/blob/f2d83ae58baaf82c8d18e0166572b903fd31bf04/code/train_la_dtc.py#L180), so if my dataset has num_classes = 2 or says 5, should i still set it to 0 or arbitrary (says k, where k < num_classes?

Thanks in advance.

**Comment by Luoxd1996** [comment]
I am sorry, I don't know what's your question. But for multi-class problems,  you can split them into many single-task. The segmentation output should have the number of class channels and the regression output has num_classes - 1 channel. For multi-class sdf computation, you can use this code (From [here](https://github.com/JunMa11/SegWithDistMap/blob/master/code/train_LA_MultiHead_SDF_L2.py)):

`def compute_sdf(img_gt, out_shape):
    """
    compute the signed distance map of binary mask
    input: segmentation, shape = (batch_size,c, x, y, z)
    output: the Signed Distance Map (SDM) 
    sdf(x) = 0; x in segmentation boundary
             -inf|x-y|; x in segmentation
             +inf|x-y|; x out of segmentation
    normalize sdf to [-1,1]
    """

    img_gt = img_gt.astype(np.uint8)
    normalized_sdf = np.zeros(out_shape)

    for b in range(out_shape[0]): # batch size
        for c in range(out_shape[1]):
            posmask = img_gt[b].astype(np.bool)
            if posmask.any():
                negmask = ~posmask
                posdis = distance(posmask)
                negdis = distance(negmask)
                boundary = skimage_seg.find_boundaries(posmask, mode='inner').astype(np.uint8)
                sdf = (negdis-np.min(negdis))/(np.max(negdis)-np.min(negdis)) - (posdis-np.min(posdis))/(np.max(posdis)-np.min(posdis))
                sdf[boundary==1] = 0
                normalized_sdf[b][c] = sdf
                assert np.min(sdf) == -1.0, print(np.min(posdis), np.max(posdis), np.min(negdis), np.max(negdis))
                assert np.max(sdf) ==  1.0, print(np.min(posdis), np.min(negdis), np.max(posdis), np.max(negdis))

    return normalized_sdf`
Best;
Xiangde.

**Comment by aprilaugust** [comment]
I'm sorry for my unclear question. 
And thanks so much for your prompt support and pointing to the multi-class sdf computation code! I will refer to it.

Could you provide an example about the shape values (shape = (batch_size, c, x, y, z)) of the 'outputs' in this line and could you mind explaining why do you set c = 0 ?
https://github.com/HiLab-git/DTC/blob/f2d83ae58baaf82c8d18e0166572b903fd31bf04/code/train_la_dtc.py#L180

Thanks a lot!

**Comment by Luoxd1996** [comment]
Hi,
First, I don't have enough time to provide you an example, I am so sorry! Second, If you read the latest reply code carefully, you can get it, the "0" just want to reduce the dimension.
Best;
Xiangde.

**Comment by aprilaugust** [comment]
I fully got it. Thanks so much for your reply.
