### ISSUE TITLE
About the FC3DDiscriminator

### ISSUE THREAD

**Issue by SkyeC77** [HiLab-git/DTC#6]
there is  "from networks.discriminator import FC3DDiscriminator" in the la_heart.py, but I do not see the discriminator file in the networks, and it seems that FC3DDiscriminator is not used in the training.  So where should I use this? Looking forward to your reply.

**Comment by Luoxd1996** [comment]
Hi, 
We don't use it, you can delete them.
Best;
Xiangde.
