### ISSUE TITLE
How to generate the predicted LSF image?

### ISSUE THREAD

**Issue by SkyeC77** [HiLab-git/DTC#7]
I want to visualize the predicted level set function in your figure1, could you tell me how to output it? I try to modify the test_util.py but failed.

**Comment by Luoxd1996** [comment]
Hi,
Sorry, I don't know what is the problem, but the LSF is predicted by the LSF branch, so you can obtain it by replacing the output branch and active function(sigmoid to tanh).
Best,
Xiangde.
